version: '3'
services:
  laravel-application:
    container_name: dmpStupefiant
    build: .
    ports:
      - 7777:80
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/storage
      - /var/www/html/bootstrap
    restart: always  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 1996:8080
